### ISSUE TITLE
Proposal peer review from josholmes

### ISSUE THREAD

**Issue by Josholmes** [INFO-526-SU24/final-project-cwjohn13#1]
The following is the peer review of the project proposal by cwjohn13. The team members that participated in this review are 

- Josh Holmes - josholmes

- Describe the goal of the project.
To determine if the popularity of environment protection movements have had an impact on trash wheels.

- Describe the data used or collected.
The data looks at autonomous trash removal devices placed at the end of rivers and stream. The data is from 4 trash wheels and show the amount of different items there were removed. 

- Describe how the research question will be answered, e.g. what approaches / methods will be used.
The author is going to see how the types of pollutants have changed over time. Going to categorize the pollutants on if the are recyclable or not. Then by looking at how these pollutants over time gage if environmental protection movements have had an impact by, I assume, the decrease in recyclable pollutants.  

- Is there anything that is unclear from the proposal?
Missing the second question. Not sure what the plan is to do for the second question. The analysis plan is not very clear on the plan and I have to make some logical guesses but I do see a path.

- Provide constructive feedback on how the team might be able to improve their project.
Come up with another question. Provides more detail on your analysis plan and how you plan on looking at the data. Not sure what data will be used to draw your conclusion.  

- What aspect of this project are you most interested in and would like to see highlighted in the presentation.
The finial result will be interesting to see if recyclable pollutants have decreased over time. 

- Provide constructive feedback on any issues with file and/or code organization.
Need more detail on the visuals you plan on making and the data from the dataset you plan on using. Need to come up with a second question to answer with the dataset. 

- (Optional) Any further comments or feedback?

**Comment by cwjohn13** [comment]
Updated analysis plan to completely describe both visualizations that I will use. In the description of the visualizations I included what data will be used in both. Verified to be sure individual projects only need one question.
Thanks for your review, it was very helpful!
