### ISSUE TITLE
Proposal peer review from VeraJSolo

### ISSUE THREAD

**Issue by VeraJSolo** [INFO-526-SU24/final-project-cwjohn13#2]
The following is the peer review of the project proposal by Vera Jackson - @VeraJSolo 

- Describe the goal of the project.
The goal of this project is to produce figures that address how impactful environment protection movements have been for the success of trash wheels by looking at the trend of pollutants over time.

- Describe the data used or collected.
The data looks at Trash Wheels and information about collection data. The data used is primarily what unique items a number of trash wheels have removed, and the date of the collection.

- Describe how the research question will be answered, e.g. what approaches / methods will be used.
The one research focus/question will be answered in two different ways. Firstly, they will look at the types of pollutants, splitting between recyclables and non-recyclables, over time. Secondly, they will look at the change in pollutants in different locations.

- Is there anything that is unclear from the proposal?
What data are you bringing in and how will you use it in the plots? Particularly, since the focus is on environment protection movements, will you highlight the year they were introduced, or when they gained popularity, and how will you define that point in time? As for location, it doesn't look like the data set includes location of trash wheels - where will you get this data from? Curious to see how you would incorporate this information into the visualizations!

- Provide constructive feedback on how the team might be able to improve their project.
Besides the previous comment, looks good! If anything, what plots do you plan on using?

- What aspect of this project are you most interested in and would like to see highlighted in the presentation.
I think this is overall a really interesting data set and question! I am interested to see how the movements impact the use of trash wheels and what types of visualizations you use! I think highlighting the year certain movements were enacted or popularized in the plots will be really cool.

- Provide constructive feedback on any issues with file and/or code organization.
The file and code organization looks fine at this stage.

- (Optional) Any further comments or feedback?
N/A

**Comment by cwjohn13** [comment]
I Updated the analysis plan to include a data set for when environmental breakthroughs occurred which will be plotted on visualizations. Also updated to include a much deeper description of what visualizations I will use.
Thank you for your review, it was very helpful.
